<a href="https://colab.research.google.com/github/thekishanpatel/Coding-Problems/blob/master/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Import NumPy**
Its a numerical library used for working with mathematical functions with multi-dimensional arrays and data-structures. 


Use less memory than normal python lists which use type pointers. 
Numpy array is designed to be an array of uniform values, without using space for type pointers.

In [0]:
import numpy as np

# **Map Python lists to NumPy Arrays**

In [0]:
x = [1,2,3]

In [3]:
np.array(x)

array([1, 2, 3])

In [0]:
x_nest =  [[1,2], [3,4], [5,6]]

In [5]:
x_nest

[[1, 2], [3, 4], [5, 6]]

In [6]:
np.array(x_nest)

array([[1, 2],
       [3, 4],
       [5, 6]])

# **Creating NumPy Arrays**

In [7]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [9]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [10]:
np.zeros(3) # Note the 0s are floating points

array([0., 0., 0.])

In [11]:
np.zeros((4,4), dtype = 'int') # Can Pass Shape

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [12]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
np.linspace(0,100,3)

array([  0.,  50., 100.])

In [14]:
np.linspace(10,50,10, dtype = 'int') # Includes stopping Points

array([10, 14, 18, 23, 27, 32, 36, 41, 45, 50])

## **Identity Matrix**

In [15]:
np.eye(10, dtype = 'int')

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

## **Creating Random Arrays**

In [16]:
np.random.rand(10) # Uniform distribution between 0 and 1

array([0.19419405, 0.35085457, 0.25827057, 0.97830774, 0.05926681,
       0.49143616, 0.07775695, 0.51447264, 0.16721218, 0.2689628 ])

In [17]:
np.random.rand(4,4) # Array Like

array([[0.08034954, 0.41960349, 0.21964494, 0.17213744],
       [0.82973664, 0.43841052, 0.34553712, 0.95769429],
       [0.78601829, 0.89255979, 0.29633713, 0.01457961],
       [0.30901537, 0.65506751, 0.22683111, 0.80559495]])

In [18]:
np.random.randn(5,5) # Standard Distribution

array([[-2.01933317,  0.26156485, -0.05911494,  1.84566328, -0.7199978 ],
       [ 0.69856638, -0.3545791 ,  0.77449581,  1.22550959, -1.03795497],
       [ 1.01166883,  2.18499424,  1.16575572, -1.53481732, -1.06548654],
       [ 1.71427263,  2.19654197, -1.23929406, -2.23359714,  0.29291741],
       [-0.64076486,  1.37324032,  0.85165526,  1.11767871, -0.51028924]])

In [19]:
np.random.randint(0, 10)

7

In [20]:
np.random.randint(1, 100, 10)

array([99, 80, 47, 73, 55, 33, 61, 47, 88, 42])

In [21]:
np.random.randint(1, 100, (4,4))

array([[ 5, 90,  2, 86],
       [34, 13, 78, 89],
       [ 5, 90, 77, 96],
       [66, 61, 35, 86]])

In [22]:
np.random.seed(42) # For Reproducibility
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

# **Array Attributes**

In [0]:
x = np.arange(25)

In [0]:
y = np.random.randint(0, 50, 10)

In [25]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [26]:
y

array([38, 18, 22, 10, 10, 23, 35, 39, 23,  2])

In [27]:
x.shape

(25,)

In [28]:
x.reshape(5,5) # Dimensions have to make sense

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [29]:
y

array([38, 18, 22, 10, 10, 23, 35, 39, 23,  2])

In [30]:
y.max()

39

In [31]:
y.argmax()

7

In [32]:
y[7]

39

In [33]:
y.dtype

dtype('int64')

# **Indexing and Selection**

In [0]:
x = np.arange(10,100,5)

In [35]:
x

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [36]:
x[5]

35

In [37]:
x[5:10]

array([35, 40, 45, 50, 55])

In [38]:
x[:5]

array([10, 15, 20, 25, 30])

In [39]:
x[5:]

array([35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95])

## **Broadcasting**

In [40]:
x

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [0]:
x[0:5] = 100

In [42]:
x

array([100, 100, 100, 100, 100,  35,  40,  45,  50,  55,  60,  65,  70,
        75,  80,  85,  90,  95])

In [0]:
x = np.arange(10,100,5)

In [44]:
x

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [0]:
x_slice = x[1:5]

In [46]:
x_slice

array([15, 20, 25, 30])

In [47]:
x

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [0]:
x_slice[:] = 1996

In [49]:
x_slice

array([1996, 1996, 1996, 1996])

In [50]:
x

array([  10, 1996, 1996, 1996, 1996,   35,   40,   45,   50,   55,   60,
         65,   70,   75,   80,   85,   90,   95])

In [0]:
x_copy = x.copy()

In [0]:
x_copy[:] = 1996

In [53]:
x_copy

array([1996, 1996, 1996, 1996, 1996, 1996, 1996, 1996, 1996, 1996, 1996,
       1996, 1996, 1996, 1996, 1996, 1996, 1996])

In [54]:
x

array([  10, 1996, 1996, 1996, 1996,   35,   40,   45,   50,   55,   60,
         65,   70,   75,   80,   85,   90,   95])

## **Indexing unto the arrays/matrices**

In [0]:
x = np.arange(5,50, 5).reshape((3,3))

In [56]:
x

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [57]:
x.shape

(3, 3)

In [58]:
x[0]

array([ 5, 10, 15])

In [59]:
x[0,0]

5

In [60]:
x[0,:]

array([ 5, 10, 15])

In [61]:
x[:,1]

array([10, 25, 40])

In [62]:
x[:2,1:]

array([[10, 15],
       [25, 30]])

In [63]:
x[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

## **Conditional Selection**

In [0]:
x = np.random.randint(1,100,10)

In [65]:
x

array([22, 53,  2, 88, 30, 38,  2, 64, 60, 21])

In [66]:
x < 50

array([ True, False,  True, False,  True,  True,  True, False, False,
        True])

In [67]:
x[x<50]

array([22,  2, 30, 38,  2, 21])

# **Operations**

In [0]:
x = np.arange(0, 25, 3)

In [69]:
x

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24])

In [70]:
x + 5 

array([ 5,  8, 11, 14, 17, 20, 23, 26, 29])

In [71]:
x + x

array([ 0,  6, 12, 18, 24, 30, 36, 42, 48])

In [72]:
x + 2*x

array([ 0,  9, 18, 27, 36, 45, 54, 63, 72])

In [73]:
np.sqrt(x)

array([0.        , 1.73205081, 2.44948974, 3.        , 3.46410162,
       3.87298335, 4.24264069, 4.58257569, 4.89897949])

In [74]:
np.sin(x)

array([ 0.        ,  0.14112001, -0.2794155 ,  0.41211849, -0.53657292,
        0.65028784, -0.75098725,  0.83665564, -0.90557836])

In [75]:
np.square(x)

array([  0,   9,  36,  81, 144, 225, 324, 441, 576])

In [76]:
x

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24])

In [77]:
x.sum()

108

In [78]:
np.sum(x)

108

In [79]:
x.var()

60.0

In [80]:
x.std()

7.745966692414834

In [81]:
x.mean()

12.0

In [0]:
x = x.reshape((3,3))

In [83]:
x

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24]])

In [84]:
x.shape

(3, 3)

In [85]:
x.sum()

108

In [86]:
x.sum(axis = 0) # ACROSS rows or sum of columns

array([27, 36, 45])

In [87]:
x.sum(axis = 1) # ACROSS columns or sum of rows

array([ 9, 36, 63])